name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:12
  
          env:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: root
            POSTGRES_DB: simple_bank
  
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      id: go 

    - name: Check out the code into the Go module directory
      uses: actions/checkout@v3

    - name:
      run: | 
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin/
       which migrate

    - name: Build
      run: go build -v ./...

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
